---
- name: Installing Petclinic web application with MySQL DB server
  hosts: web_db_server1, web_db_server2
  become: yes
  tasks:
    - include_tasks: tasks/deploy_db.yaml
    - include_tasks: tasks/deploy_web.yaml      
