---
- name: Install and Configure Web Server
  hosts: all
  become: yes

  vars:
    web_package: apache2  # Use "httpd" for RedHat-based systems
    service_name: apache2  # Use "httpd" for RedHat-based systems
    index_file_path: /var/www/html/index.html

  tasks:
    - name: Install Web Server (Debian)
      ansible.builtin.apt:
        name: "{{ web_package }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Web Server (RedHat)
      ansible.builtin.yum:
        name: "{{ web_package }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Deploy index.html
      ansible.builtin.copy:
        content: |
            <!DOCTYPE html>
            <html>
            <head>
                <title>Hello World</title>
            </head>
            <body>
                <h1>Hello, World!</h1>
            </body>
            </html>
        dest: "{{ index_file_path }}

